name: Development
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
            python-version: 3.7
      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files
  build-n-test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7","3.8","3.9", "3.10"]
    timeout-minutes: 10
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} (minimum supported python version for deltaCAT is 3.7)
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run unit tests
        run: >-
          python -m pytest
